version: '3.3'
services:
  reservations-gateway:
    container_name: gateway-container
    image: kushalgaur123/reservations-gateway:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    command: pnpm run start:prod
    env_file:
      - .env
    ports:
      - 3005:3005
      - 3000:3000
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
networks:
    nesjs-network:
      driver: bridge
